### ISSUE TITLE
Build fails on installLiberty task

### ISSUE THREAD

**Issue by davwilliams** [WASdev/sample.daytrader7#4]
**Category:** Build failure.
**Issue:** The `daytrader-ee7:installLiberty` task is failing as noted below:

```
[ant:get] Getting: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml
[ant:get] To: /var/folders/dk/tq7y0ds14b3c6srg8kd_p_ym0000gn/T/wlp-cache/index.yml
:daytrader-ee7:installLiberty FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':daytrader-ee7:installLiberty'.
> No candidates found for 8.5.+ version.
```

Reviewed the `index.yml` that was downloaded to the referenced path and it does contain the referenced for version 8.5.+ version of Liberty, as follows:

```
8.5.5_09:
    uri: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-runtime-8.5.5.9.jar
    license: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/lafiles/runtime/en.html
    extended: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-extended-8.5.5.9.jar
    kernel: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-kernel-8.5.5.9.zip
    webProfile7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-webProfile7-8.5.5.9.zip
    javaee7: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/8.5.5.9/wlp-javaee7-8.5.5.9.zip
```

Not very familiar with Gradle, so not sure what needs to be updated on the task to get it to complete successfully.

**Environment:** 

```
------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.11.5 x86_64
```
